### ISSUE TITLE
Error import _LazyBatchNorm

### ISSUE THREAD

**Issue by Tasfa** [ToriML/onnx2pytorch#22]
`from torch.nn.modules.batchnorm import _BatchNorm, _LazyBatchNorm
ImportError: cannot import name '_LazyBatchNorm' from 'torch.nn.modules.batchnorm' (/Users/xx/.pyenv/versions/3.9.6/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py)`

**Comment by ZiyuBao** [comment]
I installed torch 1.10.0 but the problem was not resolved. As I look into it, the PR merge adds _LazyBatchBase to batchnorm.py of torch instead of _LazyBatchNorm for duplication reason, and this will still cause the _LazyBatchNorm import breakdown in batchnorm.py of onnx2pytorch. Editing onnx2pytorch/operations/batchnorm.py and change _LazyBatchNorm to _LazyNormBase fixes the problem! -ZBao

**Comment by asears** [comment]
I was able to modify the script to fix the error for my case.
Using private methods is probably a bad idea, but a very helpful tool if torch authors don't provide interoperability between model formats.

```python
import warnings

from torch import nn
try:
    from torch.nn.modules.batchnorm import _BatchNorm, _LazyBatchNorm
except ImportError:
    from torch.nn.modules.batchnorm import _BatchNorm, _LazyNormBase as _LazyBatchNorm
```

Fix branch here.

<https://github.com/asears/onnx2pytorch/tree/fix_lazybatchnorm>

```shell
pip install -e onnx2pytorch
```

**Comment by calvinmccarter-at-lightmatter** [comment]
@ZiyuBao -- I think you misunderstood my comment. #23 is my PR to onnx2pytorch, not a PR to PyTorch. Did you try fetching my PR to onnx2pytorch?
